BiJiPage/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.BijiListView.as_view(),name='BIJI-Home'),
    path('post/facetoface/',views.BijiFaceListView.as_view(),name='BIJI-Face'),
    path('post/tech/',views.BijiTechListView.as_view(),name='BIJI-Tech'),
    path('post/finance/',views.BijiFinListView.as_view(),name='BIJI-Finan'),
    path('post/consult/',views.BijiConsultListView.as_view(),name='BIJI-Consult'),
    path('post/art/',views.BijiArtListView.as_view(),name='BIJI-Art'),
    path('post/manufact/',views.BijiManuListView.as_view(),name='BIJI-Manu'),
    path('post/insurance/',views.BijiInsureListView.as_view(),name='BIJI-Insur'),
    path('post/health/',views.BijiHealthListView.as_view(),name='BIJI-Health'),
    path('post/meida/',views.BijiMediaListView.as_view(),name='BIJI-Media'),
    path('post/education/',views.BijiEduListView.as_view(),name='BIJI-Edu'),
    path('post/research/',views.BijiReserachListView.as_view(),name='BIJI-Research'),
    path('post/law/',views.BijiLawListView.as_view(),name='BIJI-Law'),
    path('post/other/',views.BijiOtherListView.as_view(),name='BIJI-Other'),
    path('add/',views.BijiCreateView.as_view(),name='BIJI-Add'),
    path('<int:pk>/update/',views.BijiUpdateView.as_view(),name='BIJI-Update'),
]

XUNXINAGWEB/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from Users import views as user_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('IndexPage.urls')),
    path('lianxi/',include('LianXiPage.urls')),
    path('biji/',include('BiJiPage.urls')),
    path('joinus/',include('JoinUsPage.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='Users/login.html'),name='Login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'Users/logout.html'), name='Logout'),
    path('register/',user_view.register, name = 'Register'),
    path('profile/',user_view.profile,name='Profile'),
    path('updateprofile/',user_view.update_profile,name='Update_Profile')
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

Users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver

IDENTITY_CHOICE = [
    ('LianXiSheng','练习生'),
    ('TechDep','技术部门')
]
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank = True)
    identity = models.CharField(max_length = 20,choices = IDENTITY_CHOICE,default = 'LianXiSheng')
    authentication_Token = models.CharField(max_length = 10,null=True,blank = True)
    profile_Image = models.ImageField(default = 'default_profile.jpg',upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} profile'

    def get_identity(self):
        for pair in IDENTITY_CHOICE:
            if pair[0]==self.identity:
                return pair[1]

@receiver(post_save,sender=User)
def create_profile(sender,instance,created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save,sender=User)
def save_profile(sender,instance,**kwargs):
    instance.profile.save()
# Create your models here.

Users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.forms import ModelForm, HiddenInput
from crispy_forms.layout import Fieldset,Layout,Field
from crispy_forms.helper import FormHelper
IDENTITY_CHOICE=[
    ('LianXiSheng','练习生'),
    ('TechDep','技术部门')
]

class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email','password1','password2']
    
class ProfileRegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileRegisterForm, self).__init__(*args, **kwargs)
        self.fields['authentication_Token'].widget = HiddenInput()
    class Meta:
        model = Profile
        fields = ['identity','authentication_Token','profile_Image']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_Image']

Users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from Users.forms import UserRegisterForm
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm,UserUpdateForm,ProfileUpdateForm,ProfileRegisterForm

def register(request):
    if request.method == 'POST':
        u_form  = UserRegisterForm(request.POST)
        p_form = ProfileRegisterForm(request.POST,request.FILES)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            username = u_form.cleaned_data.get('username')
            messages.success(request,f'Account created for {username}!')
            return redirect('Login')
    else:
        u_form  = UserRegisterForm()
        p_form = ProfileRegisterForm()
    context = {
        'u_form':u_form,
        'p_form':p_form
    }
    return render(request,'Users/register.html',context)


@login_required
def profile(request):
    return render(request, 'Users/profile.html')

@login_required
def update_profile(request):
    if request.method=='POST':
        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,'Profile updated!')
            return redirect('Profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context ={
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'Users/update_profile.html',context)
# Create your views here.

Users/templates/Users/login.html
{% extends "IndexPage/base.html"%}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-infro" type="submit" style="background-color: rgb(96, 0, 134); color: antiquewhite;">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">Need an account? <a class="ml-2" style="color: rgb(17, 0, 255);" href="{% url 'Register' %}">Sign Up</a></small>
        </div>

    </div>
{% endblock content%}

Users/templates/Users/logout.html
{% extends "IndexPage/base.html"%}
{% load static %}
{% block content%}
<div class="container">

    <h2>You have been logged out!</h2>
    <div class="content-section">
        <div class="border-top pt-3">
            <a href="{% url 'Login'%}" style="color: blue;">Login Again</a>
        </div>

    </div>
</div>

{% endblock content%}

Users/templates/Users/profile.html
{% extends "IndexPage/base.html"%}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}
<style>
  .account-img {
    height: 125px;
    width: 125px;
    margin-right: 20px;
    margin-bottom: 16px;
  }
  .account-heading {
    font-size: 2.5rem;
  }
</style>
  <div class="container">
    <div class="media">
      <img class="rounded-circle account-img" src="{{user.profile.profile_Image.url}}">
      <div class="media-body">
        <h2 class="account-heading">{{user.username}}</h2>
        <p class="text-secondary">{{user.email}}</p>
        <p class="text-secondary">{{user.profile.get_identity}}</p>
        <a href="{% url 'Update_Profile'%}">Update My Profile</a>
      </div>
    </div>
  </div>
{% endblock content%}

Users/templates/Users/register.html
{% extends "IndexPage/base.html"%}
{% load static %}
{% load crispy_forms_tags %}
<script>
    // Call hideShow when page is loaded
    django.jQuery(document).ready(function(){
        django.jQuery('#id_authentication_Token').hide();
    })
//     $(document).ready(function(){
//         $('#id_authentication_Token').hide();
//     })

//     // call hideShow when the user clicks on the component_type dropdownlist
//     $('#id_identity').click(function(){
//         hideShow()
//     });

// // The jquery function below hides/shows the k_v, DI and length fields depending on the selected component_type 
// function hideShow(){
//     if(document.getElementById('id_identity') == "LianXiSheng")
//     {
//         $('#id_authentication_Token').hide();
//     }else
//     {
//         $('#id_authentication_Token').show();
//     }
// }
</script>
{% block content%}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-infro" type="submit" style="background-color: rgb(96, 0, 134); color: antiquewhite;">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">Already has An Account? <a class="ml-2" style="color: rgb(17, 0, 255);" href="{% url 'Login' %}">Sign In</a></small>
        </div>

    </div>
{% endblock content%}

Users/templates/Users/update_profile.html
{% extends "IndexPage/base.html"%}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}
<div class="container">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Update Profile</legend>
        {{ u_form|crispy }}
        {{ p_form|crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-infro" type="submit">Update!</button>
    </div>
</form>
</div>
{% endblock content%}